sonar.projectKey=NHSDigital_mesh_validate_auth_header
sonar.organization=nhsdigital
sonar.host.url=https://sonarcloud.io
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=**/*_test.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
