name: check-header-validator
on:
  pull_request:
    branches:
      - develop

jobs:

  check:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/mesh_validate_auth_header'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: make check-secrets
      - run: flutter analyze
      - run: flutter test -r expanded

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
