name: check-header-validator
on:
  pull_request:
    branches:
      - develop

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: make check-secrets
      - run: flutter analyze
      - run: flutter test -r expanded
