name: check-header-validator
on:
  pull_request:
    branches:
      - develop

jobs:

  check:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/mesh_validate_auth_header'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: 'stable'

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: make check-secrets
      - run: flutter analyze
      - run: flutter test --coverage -r expanded

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  slack-notification:
    runs-on: ubuntu-latest
    needs:
      - check
    if: ${{ always() && github.actor == 'dependabot[bot]' && contains(needs.*.result, 'failure') }}
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.DEPENDABOT_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":alarm: DEPENDABOT PR FAILED :alarm:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Checks failed for ${{ github.repository }}:${{ github.ref }} in <https://github.com/${{ github.repository }}/pull/${{ github.event.number }}|PR #${{ github.event.number }}>"
                  }
                }
              ]
            }