name: build-header-validator
on:
  push:
    branches: mm-mesh-702-create-release-build
#  pull_request:
#    branches:
#      - develop

jobs:

  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo RELEASE_VERSION="$(grep 'version:' pubspec.yaml | sed -En 's/^version:\s(.*)\+.*$/\1/p')+${{github.run_number}}" >> $GITHUB_ENV
      - uses: actions/create-release@v1
        id: create_release
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
      - run: echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}" >> $GITHUB_OUTPUT
      - run: echo "RELEASE_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT

  linux-build:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{needs.create_release.outputs.RELEASE_URL}}
      - run: echo "RELEASE_VERSION=${{needs.create_release.outputs.RELEASE_VERSION}}" >> $GITHUB_ENV

#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#
#      - run: |
#          sudo apt-get update -y
#          sudo apt-get install -y ninja-build libgtk-3-dev
#
#      - run: flutter config --enable-linux-desktop
#      - run: flutter build linux --release --build-number ${{github.run_number}}
#      - run: |
#          cd build/linux/x64/release/bundle/
#          zip -r "mesh-validate-auth-linux-${RELEASE_VERSION}.zip" .
#
#      - name: upload bundle
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: build/linux/x64/release/bundle/mesh-validate-auth-linux-${RELEASE_VERSION}.zip
#
#
#  windows-build:
#    runs-on: windows-latest
#    needs: create_release
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#
#      - run: flutter config --enable-windows-desktop
#      - run: flutter build windows --build-number ${{github.run_number}}
#      - run: ls build/windows
